---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    meta.helm.sh/release-name: nextcloud
    meta.helm.sh/release-namespace: nextcloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.1.0
  name: nextcloud-cron
  namespace: nextcloud
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: nextcloud
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: nextcloud
        spec:
          containers:
            - args:
                - '-k'
                - '--fail'
                - '-L'
                - 'http://nextcloud/cron.php'
              command:
                - curl
              image: 'curlimages/curl:7.84.0'
              imagePullPolicy: IfNotPresent
              name: nextcloud
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 2
  suspend: false


