---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: nextcloud
    meta.helm.sh/release-namespace: nextcloud
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/managed-by: Helm
    release: nextcloud
    heritage: Helm
  name: nextcloud-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    path: /volume3/k8s-nextcloud/data
    server: 192.168.50.112
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-nfs
  volumeMode: Filesystem


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: nextcloud
    meta.helm.sh/release-namespace: nextcloud
    pv.kubernetes.io/bind-completed: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/managed-by: Helm
    release: nextcloud
  name: nextcloud-storage
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeMode: Filesystem
  volumeName: nextcloud-storage
